### ISSUE TITLE
Link to the preview environment is broken on main

### ISSUE THREAD

**Issue by rberrelleza** [okteto/deploy-preview#27]
I created a PR, but the message I got was pointing to https://github.com/#/previews/website-903-cindylopez, instead of to my okteto instance. 

My action looks like this:

```
on: 
  pull_request:
    branches:
      - main

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
    - name: Login
      uses: okteto/login@master
      with:
        url: https://staging.okteto.dev
        token: ${{ secrets.OKTETO_STAGING_TOKEN }}

    - name: "Deploy the preview environment"
      uses: okteto/deploy-preview@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: website-${{ github.event.number }}-cindylopez
        scope: global
        timeout: 25m
        file: okteto-stack.yaml
```

I believe that the issue is with how https://github.com/okteto/deploy-preview/blob/master/message.go#L67 parses the token, this has changed due to `okteto context`
