### ISSUE TITLE
Using 'file' on the preview action results in an empty stack

### ISSUE THREAD

**Issue by rberrelleza** [okteto/deploy-preview#28]
I updated one of the repositories to use the 'file' param like this:

```
on: 
  pull_request:
    branches:
      - main

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
    - name: Context
      uses: okteto/context@main
      with:
        url: https://staging.okteto.dev
        token: ${{ secrets.OKTETO_STAGING_TOKEN }}

    - name: "Deploy the preview environment"
      uses: okteto/deploy-preview@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: website-${{ github.event.number }}-cindylopez
        scope: global
        timeout: 25m
        file: okteto-stack.yaml
```

When deployed in okteto, it looked like this:

![image](https://user-images.githubusercontent.com/475313/140829132-11ea851e-efba-4945-9df2-7aaeb5bf6d59.png)
