### ISSUE TITLE
Repository_dispatch jobs deploy master branch

### ISSUE THREAD

**Issue by jessedobbelaere** [okteto/deploy-preview#41]
While #39 implemented support for `repository_dispatch` events, I don't see yet how to use it when someone makes a PR from his fork. I understand the concept of using `/ok-to-test` and dispatching via `repository_dispatch`. 

However, when I print the variables in the `okteto/deploy-preview` job:

```
GITHUB_EVENT_NAME=repository_dispatch
GITHUB_REF_NAME=master
GITHUB_REF=refs/heads/master
```
Which contains master instead of the PR branch! And `okteto/deploy-preview` is figuring out the `branch` var to pass to the okteto deployer: https://github.com/okteto/deploy-preview/blob/main/entrypoint.sh#L34-L38 so it ends up passing the master branch to the okteto deployer.

So in the end this happens:
1. Someone forks your repository and creates a PR
2. You type `/ok-to-deploy sha=XXX`
3. An ok-to-deploy action is triggered which triggers an okteto-preview-deploy action (`repository_dispatch`)
4. The script in `okteto/deploy-preview` determines master branch should be deployed based on `GITHUB_REF`
5. A preview deploy is made using changes from the latest master branch, **not from the PR**

Any good suggestion to tackle this? I can make a PR, however I suppose we need to pass our custom own env var with the branch `BRANCH` since we don't have the PR number in the default env vars (it's dispatched)?

```yaml
      - name: Deploy preview environment
        uses: okteto/deploy-preview@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: 'refs/pull/${{ github.event.client_payload.pull_request.number }}/merge'
        with:
          name: ${{ env.DEPLOY_NAME }}
```

Did you also observe this @ikuradon ?
